### PR TITLE
Python 3 fixes

### PR DESCRIPTION
**Pull request by timj**
I know that no one wants to port this to python3 but we continually seem to be using it and it took me ten minutes to do a first pass. Can someone review this? I've tried it on my mac but one test file skips because I don't have obs_hsc. @parejkoj might be interested.

### CODE REVIEW

**Comment by jdswinbank** [comment]
I'm worried about this. We've seen that switching to Python 3 can cause numerical issues (DM-8030, DM-11779); while the port itself might be only ten minutes, we absolutely can't afford to spend time chasing down subtle effects which might take much longer.

**Comment by timj** [comment]
All these changes are improvements to the code in general so are perfectly acceptable to py2.

**Comment by TallJimbo** [comment]
If we are thinking about switching the shared stack to Python 3 soon, I do think this has to be a prerequisite, as much as we'd all like to stop dealing with it.

I'm fairly certain all of the actual numerics in meas_mosaic happen in C++, so I think it's less likely than with other packages that there will be subtle effects.

**Comment by jdswinbank** [comment]
Assuming that Jointcal work can converge over the next couple of months, I'd rather block the shared stack migration on meas_mosaic being retired than spend _even more_ effort fixing up meas_mosaic.

I do take the point that it's pretty unlikely these changes will cause any problems, but, well, we thought that the Python 3 port to date hadn't caused any problems until @hsinfang demonstrated that it had.

**Comment by laurenam** [comment]
So...do we have a consensus?  I'm about to poke at `meas_mosaic` for DM-11800, which will probably require a before & after check on outputs, so I would be in a good position to do that here as well if that helps decision-making.

I am wondering how @timj got this to compile given that issue?

**Comment by timj** [comment]
I might not have been building with master everything else. Life was too short to wait for afw again.

**Comment by timj** [comment]
None of these changes stop py2 working. They are making the code cleaner.

**Comment by timj** [comment]
and it will at least allow meas_mosaic to build without crashing Jenkins on py3.

**Comment by timj** [comment]
@jdswinbank Since @laurenam is going to have to do some basic tests anyhow, can we merge this even if we still continue to use py2 only?

**Comment by jdswinbank** [comment]
Yeah, I think that's fine.

**Comment by laurenam** [comment]
Wow...merged before review/testing?!

**Comment by timj** [comment]
Oh. Sorry. @parejkoj did approve it.

**Comment by laurenam** [comment]
Ah, ok...I'll do the before and after test (should that be ticketed @jdswinbank, or should I just do it and report to...where, exactly?!)

**Comment by jdswinbank** [comment]
Depends how long you expect the test to take. If it's >1 hour, it's probably worth ticketing. If there are no problems, no real need to report anything (maybe comment here). If there are problems, then ticket them for fixing. Thanks!

**Comment by laurenam** [comment]
I can confirm identical `meas_mosaic` results for py2 before and after this change for a small test dataset.  Any further testing (i.e. with py3) would require ticketing.

**Pull request merged**
